import { ArrowUpRight, BarChart3, Clock3, ExternalLink, ShieldCheck } from 'lucide-react';
import { Link } from 'wouter';
import { useGetMarketOverview, useGetMarketNews, useGetPortfolio, useGetSignals, getGetMarketOverviewQueryKey, getGetMarketNewsQueryKey, getGetPortfolioQueryKey, getGetSignalsQueryKey } from '@workspace/api-client-react';
import { EmptyBlock, ErrorBlock, LoadingBlock, Metric, SectionHeading, Sparkline } from '@/components/goldust-ui';

const money = (value = 0) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
const pct = (value = 0) => `${value >= 0 ? '+' : ''}${value.toFixed(2)}%`;
const timeAgo = (value: string) => { const mins = Math.max(1, Math.round((Date.now() - new Date(value).getTime()) / 60000)); return mins < 60 ? `${mins}m ago` : `${Math.round(mins / 60)}h ago`; };

export default function Home() {
  const market = useGetMarketOverview({ query: { queryKey: getGetMarketOverviewQueryKey() } });
  const news = useGetMarketNews({ query: { queryKey: getGetMarketNewsQueryKey() } });
  const signals = useGetSignals({ query: { queryKey: getGetSignalsQueryKey() } });
  const portfolio = useGetPortfolio({ query: { queryKey: getGetPortfolioQueryKey() } });
  const overview = market.data; const holdingData = portfolio.data;
  return <div className="mx-auto max-w-[1440px] px-5 py-9 sm:px-8 lg:px-12 lg:py-12">
    <SectionHeading eyebrow="Monday, 24 June · morning brief" title="A clearer view of your future." description="The signal beneath the noise — market context, considered risks, and small actions that compound over time." action={<span className="hidden items-center gap-2 rounded-full border border-primary/25 bg-primary/[.06] px-3 py-2 font-mono text-[9px] uppercase tracking-widest text-primary sm:flex"><ShieldCheck size={13} /> Your decisions stay yours</span>} />
    <div className="mb-8 grid gap-5 lg:grid-cols-[1.3fr_.7fr]">
      <section className="goldust-panel reveal overflow-hidden rounded-2xl p-5 sm:p-7">
        <div className="flex items-start justify-between"><div><div className="mb-3 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.2em] text-muted-foreground"><span className="h-1.5 w-1.5 rounded-full bg-primary" />Market pulse</div>{market.isLoading ? <LoadingBlock lines={2} /> : market.isError ? <ErrorBlock label="Market pulse is resting." /> : overview ? <><div className="flex flex-wrap items-end gap-x-6 gap-y-2"><span className="font-display text-5xl text-accent sm:text-6xl">{overview.regime}</span><span className="mb-1 rounded-full border border-primary/30 bg-primary/10 px-2.5 py-1 font-mono text-[10px] text-primary">{overview.regimeScore}/100 conviction</span></div><p className="mt-3 max-w-lg text-sm leading-relaxed text-muted-foreground">A measured read on the broader market. Goldust weighs breadth, momentum, and the story behind the move — not just the direction.</p></> : <EmptyBlock label="No pulse yet" detail="The market context will appear here when a source is available." />}</div><BarChart3 className="text-primary/70" size={20} /></div>
        {overview && <div className="mt-8 grid grid-cols-2 gap-5 border-t border-border pt-5 sm:grid-cols-4"><Metric label="Advancing" value={overview.breadth.advancing.toString()} detail="listed names" tone="positive" /><Metric label="Declining" value={overview.breadth.declining.toString()} detail="listed names" tone={overview.breadth.declining > overview.breadth.advancing ? 'negative' : 'default'} /><Metric label="Breadth" value={overview.breadth.sentiment} detail="market participation" /><Metric label="As of" value={new Date(overview.asOf).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} detail="latest source cut" /></div>}
      </section>
      <section className="goldust-panel reveal reveal-2 rounded-2xl p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><div className="mb-2 font-mono text-[10px] uppercase tracking-[.2em] text-primary">Nest egg · paper mode</div><p className="font-display text-4xl text-accent">{holdingData ? money(holdingData.totalValue) : '—'}</p></div><Link href="/portfolio" className="rounded-full border border-border p-2 text-muted-foreground hover:border-primary hover:text-primary" data-testid="link-open-portfolio"><ArrowUpRight size={16} /></Link></div>{portfolio.isLoading ? <LoadingBlock lines={2} /> : portfolio.isError ? <ErrorBlock label="Portfolio is taking a pause." /> : holdingData ? <><div className="mb-4 flex justify-between text-xs"><span className="text-muted-foreground">Progress to {holdingData.goal.label}</span><span className="font-mono text-primary">{Math.round(holdingData.goal.progress)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.min(100, holdingData.goal.progress)}%` }} /></div><div className="mt-5 flex justify-between text-xs text-muted-foreground"><span>Invested {money(holdingData.invested)}</span><span>Target {money(holdingData.goal.target)}</span></div></> : <EmptyBlock label="Your space is ready" detail="Start with a paper contribution when you are ready." />}</section>
    </div>
    <div className="grid gap-8 xl:grid-cols-[1.05fr_.95fr]">
      <section className="reveal reveal-2"><div className="mb-4 flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">Market board</p><h2 className="mt-2 font-display text-3xl text-accent">What is moving</h2></div><span className="font-mono text-[9px] text-muted-foreground">REAL-TIME CONTEXT</span></div>{market.isLoading ? <div className="goldust-panel rounded-2xl p-5"><LoadingBlock lines={4} /></div> : market.isError ? <ErrorBlock /> : !overview ? <EmptyBlock label="Nothing on the board" detail="Quotes appear after the next market update." /> : <div className="goldust-panel overflow-hidden rounded-2xl"><div className="border-b border-border px-5 py-3 font-mono text-[9px] uppercase tracking-[.18em] text-muted-foreground">Indices</div>{[...(overview.indices ?? []), ...(overview.crypto ?? [])].slice(0, 6).map((quote) => <div key={quote.symbol} className="flex items-center justify-between border-b border-border/70 px-5 py-4 last:border-0"><div className="flex min-w-0 items-center gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-secondary font-mono text-[10px] text-primary">{quote.symbol.slice(0, 2)}</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-accent">{quote.name}</p><p className="font-mono text-[10px] text-muted-foreground">{quote.symbol}</p></div></div><Sparkline values={quote.sparkline} positive={quote.direction !== 'down'} /><div className="w-[76px] text-right"><p className="font-mono text-xs text-accent">{quote.price.toLocaleString()}</p><p className={`mt-1 font-mono text-[10px] ${quote.direction === 'down' ? 'text-destructive' : quote.direction === 'up' ? 'text-primary' : 'text-muted-foreground'}`}>{pct(quote.changePercent)}</p></div></div>)}</div>}</section>
      <section className="reveal reveal-3"><div className="mb-4 flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">The short list</p><h2 className="mt-2 font-display text-3xl text-accent">Signals worth a look</h2></div><Link href="/signals" className="flex items-center gap-1 text-xs font-semibold text-primary hover:text-accent" data-testid="link-view-all-signals">View all <ArrowUpRight size={13} /></Link></div>{signals.isLoading ? <div className="goldust-panel rounded-2xl p-5"><LoadingBlock lines={3} /></div> : signals.isError ? <ErrorBlock /> : !signals.data?.length ? <EmptyBlock label="No active signals" detail="That is not a bad thing. Goldust will surface a view when the evidence earns it." /> : <div className="space-y-3">{signals.data.slice(0, 3).map((signal) => <div key={signal.id} className="goldust-panel rounded-2xl p-5"><div className="flex items-start justify-between gap-3"><div><div className="mb-2 flex items-center gap-2"><span className={`h-1.5 w-1.5 rounded-full ${signal.direction === 'reduce' ? 'bg-destructive' : signal.direction === 'accumulate' ? 'bg-primary' : 'bg-muted-foreground'}`} /><span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{signal.asset}</span></div><p className="text-sm font-semibold leading-relaxed text-accent">{signal.thesis}</p></div><span className="shrink-0 rounded-full bg-secondary px-2 py-1 font-mono text-[9px] uppercase text-primary">{signal.direction}</span></div><div className="mt-4 flex items-center gap-4 text-[10px] text-muted-foreground"><span>{signal.confidence}% confidence</span><span>·</span><span>{signal.horizon}</span></div></div>)}</div>}</section>
    </div>
    <section className="mt-10 border-t border-border pt-8"><div className="mb-5 flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">Context, not noise</p><h2 className="mt-2 font-display text-3xl text-accent">The stories behind the numbers</h2></div><span className="hidden font-mono text-[9px] text-muted-foreground sm:block">SOURCE-BACKED · RECENT</span></div>{news.isLoading ? <div className="grid gap-3 md:grid-cols-3"><LoadingBlock lines={3} /></div> : news.isError ? <ErrorBlock /> : !news.data?.length ? <EmptyBlock label="No stories in the brief" detail="The news brief will populate as sources arrive." /> : <div className="grid gap-3 md:grid-cols-3">{news.data.slice(0, 3).map((item) => <a key={item.id} href={item.url} target="_blank" rel="noreferrer" className="goldust-panel group rounded-2xl p-5" data-testid={`link-news-${item.id}`}><div className="mb-6 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-wider text-primary">{item.source}</span><ExternalLink size={14} className="text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></div><p className="text-sm font-semibold leading-relaxed text-accent">{item.title}</p><div className="mt-5 flex items-center gap-2 text-[10px] text-muted-foreground"><Clock3 size={12} />{timeAgo(item.publishedAt)}<span className="ml-auto rounded-full bg-secondary px-2 py-1 text-primary">{item.sentiment}</span></div></a>)}</div>}</section>
  </div>;
}