import { useState } from 'react';
import { ArrowUpRight, BookOpen, CheckCircle2, Clock3, GraduationCap, MessageCircle, Send, Sparkles } from 'lucide-react';
import { useSendChatMessage } from '@workspace/api-client-react';
import { SectionHeading } from '@/components/goldust-ui';

const concepts = [
  { title: 'Compounding', note: 'Why time can matter more than timing', tag: 'The foundation' },
  { title: 'Risk & volatility', note: 'The difference between discomfort and danger', tag: 'Build perspective' },
  { title: 'Diversification', note: 'How to avoid one story carrying the whole plan', tag: 'Design the mix' },
  { title: 'Dollar-cost averaging', note: 'A habit for investing through uncertainty', tag: 'Make it repeatable' },
  { title: 'Emergency reserves', note: 'The cash buffer behind a durable plan', tag: 'Protect the base' },
  { title: 'Fees & friction', note: 'The quiet costs that compound too', tag: 'Read the fine print' },
];

export default function Learn() {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState<{ message: string; disclaimer: string } | null>(null);
  const chat = useSendChatMessage();
  const ask = (value = question) => { if (!value.trim() || chat.isPending) return; setQuestion(value); chat.mutate({ data: { message: value } }, { onSuccess: (response) => setAnswer(response) }); };
  return <div className="mx-auto max-w-[1280px] px-5 py-9 sm:px-8 lg:px-12 lg:py-12">
    <SectionHeading eyebrow="The study room · ask anything" title="Money gets clearer when you name the idea." description="Goldust is here to make the mental models legible — not to make the decision for you. Start with a question or pick a concept below." action={<div className="hidden items-center gap-2 font-mono text-[10px] uppercase tracking-wider text-primary sm:flex"><GraduationCap size={15} /> Learn at your pace</div>} />
    <section className="relative overflow-hidden rounded-2xl border border-primary/25 bg-primary/[.06] p-5 sm:p-8"><div className="absolute -right-16 -top-24 h-64 w-64 rounded-full border border-primary/10" /><div className="absolute -right-7 -top-14 h-44 w-44 rounded-full border border-primary/10" /><div className="relative max-w-2xl"><div className="mb-4 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.2em] text-primary"><Sparkles size={14} />Ask Goldust</div><h2 className="font-display text-3xl text-accent sm:text-4xl">What are you trying to understand?</h2><div className="mt-6 flex items-center gap-2 rounded-xl border border-primary/25 bg-background px-3 py-1"><input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && ask()} placeholder="For example: how does compounding work?" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none placeholder:text-muted-foreground" data-testid="input-learn-question" /><button type="button" onClick={() => ask()} disabled={!question.trim() || chat.isPending} className="grid h-9 w-9 place-items-center rounded-lg bg-primary text-primary-foreground disabled:opacity-40" data-testid="button-ask-learn"><Send size={15} /></button></div><div className="mt-3 flex flex-wrap gap-2">{['What is a sensible time horizon?', 'How should I think about risk?', 'Why do fees matter?'].map((prompt) => <button key={prompt} type="button" onClick={() => ask(prompt)} className="rounded-full border border-border bg-background/60 px-3 py-2 text-[10px] text-muted-foreground hover:border-primary/50 hover:text-primary" data-testid={`button-suggested-${prompt.slice(0, 10).replaceAll(' ', '-').toLowerCase()}`}>{prompt}</button>)}</div></div></section>
    {chat.isPending && <div className="mt-5 rounded-2xl border border-border bg-card p-5" data-testid="status-learn-loading"><div className="flex items-center gap-3"><div className="skeleton h-8 w-8 rounded-full" /><div className="skeleton h-4 w-48 rounded" /></div><div className="skeleton mt-4 h-12 w-full rounded" /></div>}
    {chat.isError && <div className="mt-5 rounded-2xl border border-destructive/30 bg-destructive/5 p-5 text-sm text-destructive" data-testid="status-learn-error">Goldust could not answer that right now. Try asking again.</div>}
    {answer && !chat.isPending && <div className="mt-5 rounded-2xl border border-border bg-card p-5 sm:p-7 reveal" data-testid="card-learn-answer"><div className="flex gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-primary text-primary-foreground"><MessageCircle size={15} /></div><div><p className="font-mono text-[10px] uppercase tracking-wider text-primary">Goldust explains</p><p className="mt-3 text-sm leading-7 text-foreground">{answer.message}</p><div className="mt-5 border-t border-border pt-4"><p className="text-[11px] leading-relaxed text-muted-foreground"><span className="font-semibold text-accent">A useful boundary: </span>{answer.disclaimer}</p></div></div></div></div>}
    <section className="mt-11"><div className="mb-5 flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">A small curriculum</p><h2 className="mt-2 font-display text-3xl text-accent">Concepts worth carrying</h2></div><span className="hidden items-center gap-2 text-xs text-muted-foreground sm:flex"><Clock3 size={13} />Short, useful lessons</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{concepts.map((concept, index) => <button type="button" key={concept.title} onClick={() => ask(`Teach me about ${concept.title} in plain language.`)} className="goldust-panel group rounded-2xl p-5 text-left reveal" style={{ animationDelay: `${index * 45}ms` }} data-testid={`button-concept-${concept.title.toLowerCase().replaceAll(' ', '-')}`}><div className="flex items-start justify-between"><span className="grid h-9 w-9 place-items-center rounded-lg bg-secondary text-primary"><BookOpen size={16} /></span><ArrowUpRight size={15} className="text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-primary" /></div><p className="mt-7 font-mono text-[9px] uppercase tracking-wider text-primary">{concept.tag}</p><h3 className="mt-2 text-base font-semibold text-accent">{concept.title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{concept.note}</p></button>)}</div></section>
    <div className="mt-10 flex items-start gap-3 rounded-2xl border border-border bg-card/40 p-5"><CheckCircle2 className="mt-0.5 shrink-0 text-primary" size={17} /><p className="text-xs leading-relaxed text-muted-foreground">Goldust can explain concepts and show sources. It does not provide individualized financial advice, and it never guarantees an outcome.</p></div>
  </div>;
}