import { useState } from 'react';
import { Check, CircleAlert, Link2, LockKeyhole, Plus, RefreshCw, WalletCards } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { useAddContribution, useGetPortfolio, getGetPortfolioQueryKey } from '@workspace/api-client-react';
import { EmptyBlock, ErrorBlock, LoadingBlock, Metric, SectionHeading } from '@/components/goldust-ui';

const money = (value = 0) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);

export default function Portfolio() {
  const queryClient = useQueryClient();
  const query = useGetPortfolio({ query: { queryKey: getGetPortfolioQueryKey() } });
  const contribution = useAddContribution();
  const [amount, setAmount] = useState('');
  const [notice, setNotice] = useState('');
  const submit = () => { const value = Number(amount); if (!value || value < 1 || contribution.isPending) return; contribution.mutate({ data: { amount: value } }, { onSuccess: (next) => { queryClient.setQueryData(getGetPortfolioQueryKey(), next); setAmount(''); setNotice(`Paper contribution of ${money(value)} added.`); } }); };
  const portfolio = query.data;
  return <div className="mx-auto max-w-[1280px] px-5 py-9 sm:px-8 lg:px-12 lg:py-12">
    <SectionHeading eyebrow="Your long horizon · paper workspace" title="Make progress tangible." description="A calm ledger for the habit of investing. This portfolio is simulated until you deliberately connect a broker — and any future order will need your approval." action={<div className="flex items-center gap-2 rounded-full border border-primary/25 bg-primary/[.06] px-3 py-2 font-mono text-[9px] uppercase tracking-widest text-primary"><WalletCards size={13} />Paper mode</div>} />
    {query.isLoading ? <div className="goldust-panel rounded-2xl p-7"><LoadingBlock lines={5} /></div> : query.isError ? <ErrorBlock label="Your paper portfolio could not load." /> : !portfolio ? <EmptyBlock label="Your nest egg starts here" detail="Add a paper contribution to give the plan a first shape." /> : <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="goldust-panel rounded-2xl p-5 sm:p-6"><Metric label="Total value" value={money(portfolio.totalValue)} detail={portfolio.mode === 'paper' ? 'simulated market value' : 'connected account'} /></div><div className="goldust-panel rounded-2xl p-5 sm:p-6"><Metric label="Invested" value={money(portfolio.invested)} detail={`${money(portfolio.cash)} available cash`} /></div><div className="goldust-panel rounded-2xl p-5 sm:p-6"><Metric label="Gain" value={`${portfolio.gain >= 0 ? '+' : ''}${money(portfolio.gain)}`} detail={`${portfolio.gainPercent.toFixed(2)}% since start`} tone={portfolio.gain >= 0 ? 'positive' : 'negative'} /></div><div className="goldust-panel rounded-2xl p-5 sm:p-6"><Metric label="Goal progress" value={`${Math.round(portfolio.goal.progress)}%`} detail={`toward ${money(portfolio.goal.target)}`} tone="positive" /></div></div>
      <div className="mt-8 grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><section><div className="mb-4 flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">Allocation</p><h2 className="mt-2 font-display text-3xl text-accent">What you hold</h2></div><span className="font-mono text-[9px] text-muted-foreground">{portfolio.holdings.length} positions</span></div><div className="goldust-panel overflow-hidden rounded-2xl">{portfolio.holdings.length ? portfolio.holdings.map((holding) => <div key={holding.symbol} className="flex items-center justify-between gap-3 border-b border-border/70 px-5 py-4 last:border-0" data-testid={`row-holding-${holding.symbol}`}><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-secondary font-mono text-[10px] text-primary">{holding.symbol.slice(0, 2)}</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-accent">{holding.name}</p><p className="font-mono text-[10px] text-muted-foreground">{holding.symbol} · {holding.quantity} units</p></div></div><div className="hidden h-1.5 w-20 overflow-hidden rounded-full bg-secondary sm:block"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.min(100, holding.allocation)}%` }} /></div><div className="text-right"><p className="font-mono text-xs text-accent">{money(holding.value)}</p><p className={`mt-1 font-mono text-[10px] ${holding.changePercent >= 0 ? 'text-primary' : 'text-destructive'}`}>{holding.changePercent >= 0 ? '+' : ''}{holding.changePercent.toFixed(2)}%</p></div></div>) : <div className="p-6"><EmptyBlock label="No holdings yet" detail="Your first paper contribution can begin the allocation." /></div>}</div></section>
        <section><div className="mb-4"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">Keep the habit</p><h2 className="mt-2 font-display text-3xl text-accent">Add a contribution</h2></div><div className="goldust-panel rounded-2xl p-5 sm:p-6"><p className="text-sm leading-relaxed text-muted-foreground">See how a deposit changes the plan without moving real money. This is a simulation, not a broker instruction.</p><label className="mt-6 block font-mono text-[9px] uppercase tracking-wider text-muted-foreground" htmlFor="contribution-amount">Amount</label><div className="mt-2 flex items-center rounded-xl border border-input bg-background px-3"><span className="font-display text-xl text-primary">$</span><input id="contribution-amount" type="number" min="1" value={amount} onChange={(event) => { setAmount(event.target.value); setNotice(''); }} placeholder="250" className="w-full bg-transparent px-2 py-3 font-mono text-sm outline-none placeholder:text-muted-foreground" data-testid="input-contribution-amount" /></div><button type="button" onClick={submit} disabled={contribution.isPending || !amount || Number(amount) < 1} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50" data-testid="button-add-contribution">{contribution.isPending ? <RefreshCw className="animate-spin" size={15} /> : <Plus size={15} />} {contribution.isPending ? 'Adding to paper ledger' : 'Add paper contribution'}</button>{notice && <p className="mt-3 flex items-center gap-2 text-xs text-primary" data-testid="status-contribution-success"><Check size={14} />{notice}</p>}{contribution.isError && <p className="mt-3 text-xs text-destructive" data-testid="status-contribution-error">That contribution could not be added. Nothing was changed.</p>}</div></section></div>
      <section className="mt-8 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-primary/20 bg-primary/[.05] p-5"><div className="flex gap-3"><CircleAlert className="shrink-0 text-primary" size={17} /><div><p className="text-sm font-semibold text-accent">Approval is part of the design</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Goldust may prepare a future broker action, but it will never place an order autonomously. You stay in control.</p></div></div></div><div className="rounded-2xl border border-border bg-card/50 p-5"><div className="flex gap-3"><LockKeyhole className="shrink-0 text-muted-foreground" size={17} /><div><p className="text-sm font-semibold text-accent">Connection readiness</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Live broker connections are not enabled yet. Your paper workspace remains separate and safe to explore.</p><span className="mt-3 inline-flex items-center gap-1 font-mono text-[9px] uppercase tracking-wider text-muted-foreground"><Link2 size={11} />Not connected</span></div></div></div></section></>}
  </div>;
}