import { useMemo, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, BookOpen, ChevronDown, CircleAlert, ExternalLink, Filter, Minus } from 'lucide-react';
import { useGetSignals, getGetSignalsQueryKey } from '@workspace/api-client-react';
import { EmptyBlock, ErrorBlock, LoadingBlock, SectionHeading } from '@/components/goldust-ui';

const directionCopy = { accumulate: 'Accumulate', watch: 'Watch', reduce: 'Reduce' };

export default function Signals() {
  const [filter, setFilter] = useState('all');
  const query = useGetSignals({ query: { queryKey: getGetSignalsQueryKey() } });
  const signals = useMemo(() => (query.data ?? []).filter((signal) => filter === 'all' || signal.direction === filter), [query.data, filter]);
  return <div className="mx-auto max-w-[1280px] px-5 py-9 sm:px-8 lg:px-12 lg:py-12">
    <SectionHeading eyebrow="Evidence ledger · refreshed today" title="Signals, with the why attached." description="Directional views are only useful when you can inspect the assumptions beneath them. Read the thesis, weigh the risks, and decide what earns your attention." action={<div className="hidden items-center gap-2 font-mono text-[10px] uppercase tracking-wider text-muted-foreground sm:flex"><Filter size={13} /> Sort by evidence</div>} />
    <div className="mb-6 flex items-center gap-2 overflow-x-auto border-b border-border pb-4">{['all', 'accumulate', 'watch', 'reduce'].map((value) => <button type="button" key={value} onClick={() => setFilter(value)} className={`whitespace-nowrap rounded-full px-3 py-2 font-mono text-[10px] uppercase tracking-wider transition-colors ${filter === value ? 'bg-primary text-primary-foreground' : 'border border-border text-muted-foreground hover:border-primary/50 hover:text-primary'}`} data-testid={`button-filter-${value}`}>{value === 'all' ? 'All views' : directionCopy[value as keyof typeof directionCopy]}</button>)}</div>
    {query.isLoading ? <div className="space-y-4"><div className="goldust-panel rounded-2xl p-6"><LoadingBlock lines={4} /></div><div className="goldust-panel rounded-2xl p-6"><LoadingBlock lines={4} /></div></div> : query.isError ? <ErrorBlock label="The signal ledger could not load." /> : !signals.length ? <EmptyBlock label={filter === 'all' ? 'No signals right now' : `No ${filter} views right now`} detail="A quiet ledger is a useful signal too. Goldust will not fill the space with noise." /> : <div className="space-y-4">{signals.map((signal, index) => <SignalCard key={signal.id} signal={signal} index={index} />)}</div>}
    <div className="mt-8 flex items-start gap-3 rounded-2xl border border-primary/20 bg-primary/[.05] p-5"><CircleAlert className="mt-0.5 shrink-0 text-primary" size={17} /><div><p className="text-sm font-semibold text-accent">How to use a Goldust signal</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Confidence describes the model's confidence in its current read, not a probability of profit. Every view has a horizon and a risk case for a reason.</p></div></div>
  </div>;
}

function SignalCard({ signal, index }: { signal: any; index: number }) {
  const [expanded, setExpanded] = useState(index === 0);
  const ActionIcon = signal.direction === 'accumulate' ? ArrowUpRight : signal.direction === 'reduce' ? ArrowDownRight : Minus;
  const tone = signal.direction === 'accumulate' ? 'text-primary bg-primary/10 border-primary/25' : signal.direction === 'reduce' ? 'text-destructive bg-destructive/10 border-destructive/25' : 'text-muted-foreground bg-secondary border-border';
  return <article className="goldust-panel rounded-2xl p-5 sm:p-7 reveal" style={{ animationDelay: `${index * 70}ms` }} data-testid={`card-signal-${signal.id}`}>
    <div className="flex flex-col gap-5 sm:flex-row sm:items-start"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl border ${tone}`}><ActionIcon size={20} /></div><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">{signal.asset}</span><span className="text-border">/</span><span className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">{signal.horizon} horizon</span></div><h2 className="max-w-3xl font-display text-2xl leading-tight text-accent sm:text-3xl">{signal.thesis}</h2><div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-muted-foreground"><span><strong className="font-mono text-primary">{signal.confidence}%</strong> confidence</span><span>Risk: <strong className="text-foreground">{signal.risk}</strong></span></div></div><button type="button" onClick={() => setExpanded((value) => !value)} className="flex shrink-0 items-center gap-2 self-end rounded-lg border border-border px-3 py-2 text-xs text-muted-foreground hover:border-primary hover:text-primary sm:self-start" data-testid={`button-expand-signal-${signal.id}`}>{expanded ? 'Hide detail' : 'Inspect view'}<ChevronDown size={14} className={`transition-transform ${expanded ? 'rotate-180' : ''}`} /></button></div>
    {expanded && <div className="mt-7 grid gap-6 border-t border-border pt-6 md:grid-cols-[1fr_.72fr] reveal"><div><div className="mb-3 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground"><BookOpen size={13} className="text-primary" />What is driving it</div><ul className="space-y-3">{signal.drivers.map((driver: string, driverIndex: number) => <li key={driverIndex} className="flex gap-3 text-sm leading-relaxed text-foreground"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-primary" />{driver}</li>)}</ul></div><div className="rounded-xl bg-secondary/60 p-4"><div className="mb-3 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground"><CircleAlert size={13} className="text-destructive" />What could break it</div><p className="text-sm leading-relaxed text-muted-foreground">{signal.risk}</p>{signal.sources?.length > 0 && <div className="mt-5 border-t border-border pt-4"><div className="mb-2 font-mono text-[9px] uppercase tracking-wider text-muted-foreground">Sources</div>{signal.sources.map((source: string, sourceIndex: number) => <a key={sourceIndex} href={source} target="_blank" rel="noreferrer" className="mb-1 flex items-center gap-1 truncate text-xs text-primary hover:text-accent" data-testid={`link-signal-source-${signal.id}-${sourceIndex}`}>Source {sourceIndex + 1}<ExternalLink size={11} /></a>)}</div>}</div></div>}
  </article>;
}